
import { MarketingStrategy } from '../types';

export const PROVEN_STRATEGIES: MarketingStrategy[] = [
  { 
    id: 'janads_master', 
    name: '01. JAN ADS MASTER (GOD MODE)', 
    category: 'OMNICHANNEL', 
    creativesNeeded: 20, 
    description: 'Arquitectura de élite: 4 AdSets que cubren desde Prospecting hasta Retargeting y Lookalikes.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 100000,
    platforms: ['META'],
    structure: [
      { name: "C1: Prospecting - Broad Absoluto", budgetPercentage: 30, funnelStage: 'COLD', targeting: { type: 'BROAD' } },
      { name: "C2: High-Intent - Marketing & Business", budgetPercentage: 30, funnelStage: 'COLD', targeting: { type: 'INTERESTS', interests: ['Business', 'E-commerce'] } },
      { name: "C3: Lookalike Expansion", budgetPercentage: 20, funnelStage: 'WARM', targeting: { type: 'RETARGETING' } },
      { name: "C4: Retargeting - Engagers", budgetPercentage: 20, funnelStage: 'HOT', targeting: { type: 'RETARGETING' } }
    ],
    segmentationLogic: 'Estructura 3-Tier: Conquista de audiencias frías y cierre por comportamiento.',
    detailedSegmentation: 'Optimización Advantage+ con expansión de intereses activada.',
    platformDetails: [
      { platform: 'META', format: '9:16', items: ['4 Reels Dinámicos'] },
      { platform: 'META', format: '1:1', items: ['6 Imágenes Estáticas'] }
    ]
  },
  { 
    id: 'andromeda_broad', 
    name: '02. ANDRÓMEDA: ESCALADO BROAD 2.0', 
    category: 'META', 
    creativesNeeded: 10, 
    description: 'Foco en Advantage+ Shopping. Creative-as-Targeting puro.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 30000,
    platforms: ['META'],
    structure: [{ name: "Andrómeda - Ventas Directas", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Algorítmica 100%. Sin intereses manuales.',
    detailedSegmentation: 'Deja que el pixel optimice basándose en el CTR de los creativos.',
    platformDetails: [{ platform: 'META', format: '9:16', items: ['Videos de Gancho Rápido'] }]
  },
  { 
    id: 'waba_direct', 
    name: '03. WABA: CIERRE WHATSAPP', 
    category: 'META', 
    creativesNeeded: 5, 
    description: 'Embudo directo a WhatsApp para cierre manual de alta conversión.', 
    objective: 'OUTCOME_TRAFFIC', 
    minBudget: 15000,
    platforms: ['META'],
    structure: [{ name: "WABA - Tráfico Local", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'INTERESTS', interests: ['Ventas'] } }],
    segmentationLogic: 'Geolocalización + Intención de Mensaje.',
    detailedSegmentation: 'Filtra por usuarios con alta probabilidad de iniciar conversaciones.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['CTA: Enviar Mensaje'] }]
  },
  { 
    id: 'the_blitz', 
    name: '04. THE BLITZ: IMPACTO RÁPIDO', 
    category: 'OMNICHANNEL', 
    creativesNeeded: 15, 
    description: 'Campañas agresivas de 7 días para lanzamientos flash.', 
    objective: 'OUTCOME_AWARENESS', 
    minBudget: 50000,
    platforms: ['META', 'TIKTOK'],
    structure: [{ name: "Blitz - Saturación", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Saturación por frecuencia máxima.',
    detailedSegmentation: 'Alcance masivo en ventanas cortas de tiempo.',
    platformDetails: [{ platform: 'META', format: '9:16', items: ['Reels Agresivos'] }]
  },
  { 
    id: 'evergreen_empire', 
    name: '05. EVERGREEN EMPIRE', 
    category: 'META', 
    creativesNeeded: 12, 
    description: 'Estabilidad a largo plazo con rotación automática de anuncios.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 40000,
    platforms: ['META'],
    structure: [{ name: "Empire - Consistencia", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'INTERESTS', interests: ['Shopping'] } }],
    segmentationLogic: 'Baja frecuencia, alta relevancia.',
    detailedSegmentation: 'Mantenimiento de ROAS estable mediante IA.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Carruseles'] }]
  },
  { 
    id: 'viral_pulse', 
    name: '06. VIRAL PULSE (TIKTOK FOCUS)', 
    category: 'TIKTOK', 
    creativesNeeded: 8, 
    description: 'Contenido UGC para viralización orgánica pagada.', 
    objective: 'OUTCOME_TRAFFIC', 
    minBudget: 20000,
    platforms: ['TIKTOK'],
    structure: [{ name: "Pulse - UGC Viral", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'TikTok Creative Exchange logic.',
    detailedSegmentation: 'Foco en los primeros 3 segundos de video.',
    platformDetails: [{ platform: 'TIKTOK', format: '9:16', items: ['UGC Ads'] }]
  },
  { 
    id: 'google_sniper', 
    name: '07. GOOGLE SNIPER (SEARCH)', 
    category: 'GOOGLE', 
    creativesNeeded: 10, 
    description: 'Captura de demanda existente con palabras clave de alta intención.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 35000,
    platforms: ['GOOGLE'],
    structure: [{ name: "Sniper - Keywords", budgetPercentage: 100, funnelStage: 'HOT', targeting: { type: 'INTERESTS', interests: ['Buy now'] } }],
    segmentationLogic: 'Intención de búsqueda pura.',
    detailedSegmentation: 'Concordancia exacta en términos de compra.',
    platformDetails: [{ platform: 'GOOGLE', format: 'TEXT', items: ['Anuncios de Búsqueda'] }]
  },
  { 
    id: 'multi_touch', 
    name: '08. MULTI-TOUCH ATTRIBUTION', 
    category: 'OMNICHANNEL', 
    creativesNeeded: 25, 
    description: 'Presencia en todos los puntos de contacto del cliente.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 150000,
    platforms: ['META', 'GOOGLE', 'TIKTOK'],
    structure: [{ name: "Omni - Omnipresencia", budgetPercentage: 100, funnelStage: 'WARM', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Retargeting cruzado entre plataformas.',
    detailedSegmentation: 'Sincronización de audiencias vía API.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Feed Ads'] }]
  },
  { 
    id: 'low_ticket_scale', 
    name: '09. LOW-TICKET SCALE', 
    category: 'META', 
    creativesNeeded: 15, 
    description: 'Escalado masivo de productos por debajo de $30.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 25000,
    platforms: ['META'],
    structure: [{ name: "Scale - Volumen", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Optimización por volumen de compras.',
    detailedSegmentation: 'Expansión rápida basada en CAPI.',
    platformDetails: [{ platform: 'META', format: '9:16', items: ['Reels de Venta Directa'] }]
  },
  { 
    id: 'high_ticket_auth', 
    name: '10. HIGH-TICKET AUTHORITY', 
    category: 'META', 
    creativesNeeded: 10, 
    description: 'Venta de servicios/productos caros mediante autoridad.', 
    objective: 'OUTCOME_LEADS', 
    minBudget: 60000,
    platforms: ['META'],
    structure: [{ name: "Auth - Lead Gen", budgetPercentage: 100, funnelStage: 'WARM', targeting: { type: 'INTERESTS', interests: ['Luxury'] } }],
    segmentationLogic: 'Filtrado por poder adquisitivo.',
    detailedSegmentation: 'Exclusión de audiencias de bajo interés.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Video Testimonios'] }]
  },
  { 
    id: 'local_conqueror', 
    name: '11. LOCAL CONQUEROR', 
    category: 'META', 
    creativesNeeded: 5, 
    description: 'Dominio de zonas geográficas específicas.', 
    objective: 'OUTCOME_TRAFFIC', 
    minBudget: 10000,
    platforms: ['META'],
    structure: [{ name: "Local - Geo", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Radio de 5km alrededor del negocio.',
    detailedSegmentation: 'Foco en residentes locales.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Local Awareness'] }]
  },
  { 
    id: 'app_growth', 
    name: '12. APP GROWTH HACK', 
    category: 'GOOGLE', 
    creativesNeeded: 15, 
    description: 'Instalaciones masivas para apps móviles.', 
    objective: 'OUTCOME_TRAFFIC', 
    minBudget: 45000,
    platforms: ['GOOGLE'],
    structure: [{ name: "App - Installs", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Campaña de Aplicación de Google.',
    detailedSegmentation: 'Optimización por costo por instalación (CPI).',
    platformDetails: [{ platform: 'GOOGLE', format: '9:16', items: ['App Promo'] }]
  },
  { 
    id: 'b2b_authority', 
    name: '13. B2B META AUTHORITY', 
    category: 'META', 
    creativesNeeded: 8, 
    description: 'Llegar a dueños de negocio en Facebook e Instagram.', 
    objective: 'OUTCOME_LEADS', 
    minBudget: 50000,
    platforms: ['META'],
    structure: [{ name: "B2B - Business Admins", budgetPercentage: 100, funnelStage: 'WARM', targeting: { type: 'INTERESTS', interests: ['Business Owner'] } }],
    segmentationLogic: 'Targeting por cargo y comportamiento.',
    detailedSegmentation: 'Filtro por administradores de páginas.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Whitepaper Ads'] }]
  },
  { 
    id: 'flash_frenzy', 
    name: '14. FLASH SALE FRENZY', 
    category: 'META', 
    creativesNeeded: 20, 
    description: 'Liquidación de stock en 48-72 horas.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 30000,
    platforms: ['META'],
    structure: [{ name: "Flash - Urgencia", budgetPercentage: 100, funnelStage: 'HOT', targeting: { type: 'RETARGETING' } }],
    segmentationLogic: 'Máxima urgencia y escasez.',
    detailedSegmentation: 'Retargeting de lista de clientes.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Banner de Descuento'] }]
  },
  { 
    id: 'cart_rescue', 
    name: '15. ABANDONED CART RECOVERY 2.0', 
    category: 'META', 
    creativesNeeded: 6, 
    description: 'Recuperar ventas perdidas con ofertas dinámicas.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 15000,
    platforms: ['META'],
    structure: [{ name: "Rescue - Dynamic", budgetPercentage: 100, funnelStage: 'HOT', targeting: { type: 'RETARGETING' } }],
    segmentationLogic: 'Anuncios dinámicos de producto (DPA).',
    detailedSegmentation: 'Usuarios que agregaron al carrito pero no compraron.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Catálogo Dinámico'] }]
  },
  { 
    id: 'content_machine', 
    name: '16. CONTENT MACHINE (UGC)', 
    category: 'TIKTOK', 
    creativesNeeded: 12, 
    description: 'Transformar contenido orgánico en pauta de alto CTR.', 
    objective: 'OUTCOME_TRAFFIC', 
    minBudget: 25000,
    platforms: ['TIKTOK'],
    structure: [{ name: "Machine - UGC Spark", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Spark Ads con influencers.',
    detailedSegmentation: 'Amplificación de videos con alto engagement orgánico.',
    platformDetails: [{ platform: 'TIKTOK', format: '9:16', items: ['Spark Ads'] }]
  },
  { 
    id: 'aesthetic_rebrand', 
    name: '17. AESTHETIC REBRAND', 
    category: 'META', 
    creativesNeeded: 10, 
    description: 'Cambio de imagen de marca con visuales de IA.', 
    objective: 'OUTCOME_AWARENESS', 
    minBudget: 30000,
    platforms: ['META'],
    structure: [{ name: "Rebrand - Luxury", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Enfoque visual premium.',
    detailedSegmentation: 'Mejora de la percepción de marca mediante estética.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Brand Story'] }]
  },
  { 
    id: 'pmax_power', 
    name: '18. ECOM POWER-UP (PMAX)', 
    category: 'GOOGLE', 
    creativesNeeded: 20, 
    description: 'Aprovechar Google Performance Max al máximo.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 70000,
    platforms: ['GOOGLE'],
    structure: [{ name: "PMax - Full Funnel", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'IA de Google 360.',
    detailedSegmentation: 'Uso de señales de audiencia propietarias.',
    platformDetails: [{ platform: 'GOOGLE', format: 'OMNI', items: ['Asset Groups'] }]
  },
  { 
    id: 'lead_magnet', 
    name: '19. LEAD MAGNET FUNNEL', 
    category: 'META', 
    creativesNeeded: 10, 
    description: 'Captar correos/teléfonos a cambio de valor gratuito.', 
    objective: 'OUTCOME_LEADS', 
    minBudget: 20000,
    platforms: ['META'],
    structure: [{ name: "Magnet - Freebie", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'INTERESTS', interests: ['Free stuff'] } }],
    segmentationLogic: 'Venta de la "Suscripción".',
    detailedSegmentation: 'Formularios instantáneos nativos de Meta.',
    platformDetails: [{ platform: 'META', format: '1:1', items: ['Instant Forms'] }]
  },
  { 
    id: 'dark_post_scale', 
    name: '20. DARK POST SCALING', 
    category: 'META', 
    creativesNeeded: 30, 
    description: 'Escalado invisible: Múltiples variaciones sin saturar el feed.', 
    objective: 'OUTCOME_SALES', 
    minBudget: 200000,
    platforms: ['META'],
    structure: [{ name: "Dark - Invisible", budgetPercentage: 100, funnelStage: 'COLD', targeting: { type: 'BROAD' } }],
    segmentationLogic: 'Prueba masiva de creativos.',
    detailedSegmentation: 'Identificación de "Winning Ads" en segundos.',
    platformDetails: [{ platform: 'META', format: '9:16', items: ['Shadow Reels'] }]
  }
];
